### ISSUE TITLE
Kegg's find function

### ISSUE THREAD

**Issue by MehmetAzizYirik** [cokelaer/bioservices#63] opened 2016-07-01 15:31 UTC
Hi

I used the bioservices' KEGG function called "find" to extract ligand information for a list of proteins and it returned three ligand IDs. Accordingly I just wanted to check manually the ligand IDs and there is just a ligand for a protein not for the other. Even the IDs returned by the find function does not work; snce I searched the IDs on KEGG database and it was written that " no such data" I dont understand actually depending on what or how the function gave the two IDs which KEGG database does not include. I just wanted to share the problem with you maybe you need to check the find function again.

All the Best;
Aziz

**Comment by cokelaer** [comment] 2016-09-05 22:25
Do you happen to have an example ?

**Comment by MehmetAzizYirik** [comment] 2016-09-05 22:28
Dear Thomas;

Actually I could not find a function or example for KEGG. I just used the
Bioservices function and found that just for a protein there is a ligand
information. This is all I have done for KEGG.

Do you have any idea for it ?

All the Best;
Aziz

6 Eyl 2016 01:25 tarihinde "Thomas Cokelaer" <notifications@github.com>
yazdı:

**Comment by cokelaer** [comment] 2017-06-25 20:03
Without an example, I am closing this issue since I cannot reproduce the issue.

**Closed by cokelaer** 2017-06-25 20:03 UTC
Labels: wontfix

**Comment by MehmetAzizYirik** [comment] 2017-06-27 16:29
Ok thanks for informing.


Have you received my emails about the PhD application to the Pasteur Institute ? I sent two emails to you.


Kind Regards,

Aziz

________________________________
