### ISSUE TITLE
uniprot.mapping not working

### ISSUE THREAD

**Issue by asulit08** [cokelaer/bioservices#132] opened 2018-07-31 04:41 UTC
Hi, I've just installed bioservices through conda (and I've tried pip as well) and I'm following the tutorials. When I tried the **'u.mapping("ACC", "KEGG_ID", query='P43403')'** command, I either get the following:

__**_defaultdict(list,
            {'"/";': ['}'],
             '#browserwarning': ['{'],
             "$('#basket').hide();": ['}'],
             '&&': ['""'],
             '&apos;;"': ['class="searchBoxIndicator"'],
             "'/';": ['var'],
             "'UA-6228219-1',": ["'auto');"],
             "'forceSSL',": ['true);'],
             "'uniparc'": [':'],
             '(!name.startsWith("_")': ['&&'],
             '(System': ['generated'],
             '(UniRef)</a></li><li><a': ['href="/uniparc">Sequence'],
             '(false)': ['{'],
             '(function()': ['{'],
             '(new': ['upload()).uploadLinkHandler();"'],
             '(var': ['i', 'j'],
             '+': ['"=\'\';expires="+new', '"=\'\';expires="+new'],
             '-1)': ['{'],
             '0;': ['}'],
             '2002': ['&ndash;'],
             ':': ['case'],
             ';': ['i', '</script><meta'],
             '<': ['cookieString.length;'],
             '<!--[if': ['lte'],
             '</a><script': ['type="text/javascript">'],
             '</div><div': ['onclick="location.href=&apos;/help/text-search&apos;;"',
              'onclick="location.href=&apos;/help/advanced_search'],
               ...and so on_       

or when I use **'u.mapping(fr="ACC", to="KEGG_ID", query='P43403')**', 

I get the following:

             _values = result[1::2]
             for i, key in enumerate(keys):
                result_dict[key].append(values[i])
         return result_dict
IndexError: list index out of range__

I installed bioservices 1.5.2 

I hope you can help, thanks!

**Comment by cokelaer** [comment] 2018-08-01 05:38
There is probably a new kind of http protocol on uniprot side. For now, it looks like executing the command twice will return the correct answer. I will see if it can be fixed. This is obviously not the intended behaviour but it will work for now. you can do for instance:

    u.search("P43403")
    u.mapping("ACC", "KEGG_ID", "P43403")

**Comment by cokelaer** [comment] 2018-08-01 07:53
I've just tried again and it seems to work now. Sometimes, services have temporary wierd behaviour. This may have happen in this instance. I used bioservices 1.5.2 as well (latest version). @asulit08  Can you try again and let me know if you are still experiencing this issue. thanks in advance

**Comment by asulit08** [comment] 2018-08-01 23:16
Hi, I'm afraid it's still not working properly for me. I'm still getting the same errors. Plus, I tried using u.search("P43403") and I keep getting the following results:

_"'Entry\tEntry name\tStatus\tProtein names\tGene names\tOrganism\tLength\nP43403\tZAP70_HUMAN\treviewed\tTyrosine-protein kinase ZAP-70 (EC 2.7.10.2) (70 kDa zeta-chain associated protein) (Syk-related tyrosine kinase)\tZAP70 SRK\tHomo sapiens (Human)\t619\nQ9Y2R2\tPTN22_HUMAN\treviewed\tTyrosine-protein phosphatase non-receptor type 22 (EC 3.1.3.48) (Hematopoietic cell protein-tyrosine phosphatase 70Z-PEP) (Lymphoid phosphatase) (LyP) (PEST-domain phosphatase) (PEP)\tPTPN22 PTPN8\tHomo sapiens (Human)\t807\nP07766\tCD3E_HUMAN\treviewed\tT-cell surface glycoprotein CD3 epsilon chain (T-cell surface antigen T3/Leu-4 epsilon chain) (CD antigen CD3e)\tCD3E T3E\tHomo sapiens (Human)\t207\nP22681\tCBL_HUMAN\treviewed\tE3 ubiquitin-protein ligase CBL (EC 2.3.2.27) (Casitas B-lineage lymphoma proto-oncogene) (Proto-oncogene c-Cbl) (RING finger protein 55) (RING-type E3 ubiquitin transferase CBL) (Signal transduction protein CBL)\tCBL CBL2 RNF55\tHomo sapiens (Human)\t906\nP20963\tCD3Z_HUMAN\treviewed\tT-cell surface glycoprotein CD3 zeta chain (T-cell receptor T3 zeta chain) (CD antigen CD247)\tCD247 CD3Z T3Z TCRZ\tHomo sapiens (Human)\t164\nP00533\tEGFR_HUMAN\treviewed\tEpidermal growth factor receptor (EC 2.7.10.1) (Proto-oncogene c-ErbB-1) (Receptor tyrosine-protein kinase erbB-1)\tEGFR ERBB ERBB1 HER1\tHomo sapiens (Human)\t1210\nP08581\tMET_HUMAN\treviewed\tHepatocyte growth factor receptor (HGF receptor) (EC 2.7.10.1) (HGF/SF receptor) (Proto-oncogene c-Met) (Scatter factor receptor) (SF receptor) (Tyrosine-protein kinase Met)\tMET\tHomo sapiens (Human)\t1390\nP10721\tKIT_HUMAN\treviewed\tMast/stem cell growth factor receptor Kit (SCFR) (EC 2.7.10.1) (Piebald trait protein) (PBT) (Proto-oncogene c-Kit) (Tyrosine-protein kinase Kit) (p145 c-kit) (v-kit Hardy-Zuckerman 4 feline sarcoma viral oncogene homolog) (CD antigen CD117)\tKIT SCFR\tHomo sapiens (Human)\t976\nP06239\tLCK_HUMAN\treviewed\tTyrosine-protein kinase Lck (EC 2.7.10.2) (Leukocyte C-terminal Src kinase) (LSK) (Lymphocyte cell-specific protein-tyrosine kinase) (Protein YT16) (Proto-oncogene Lck) (T cell-specific protein-tyrosine kinase) (p56-LCK)\tLCK\tHomo sapiens (Human)\t509\nQ8BGG7\tUBS3B_MOUSE\treviewed\tUbiquitin-associated and SH3 domain-containing protein B (EC 3.1.3.48) (Cbl-interacting protein p70) (Suppressor of T-cell receptor signaling 1) (STS-1) (T-cell ubiquitin ligand 2) (TULA-2) (Tyrosine-protein phosphatase STS1/TULA2)\tUbash3b Sts1\tMus musculus (Mouse)\t638\nQ8N1K5\tTHMS1_HUMAN\treviewed\tProtein THEMIS (Thymocyte-expressed molecule involved in selection)\tTHEMIS C6orf190 C6orf207\tHomo sapiens (Human)\t641\n'"_

which I suspect may be correct, but in a weird format?

Thank you

**Comment by JamesPino** [comment] 2018-08-02 00:59
I think switching to https from http should work.  At least for u.mapping

**Comment by asulit08** [comment] 2018-08-02 01:14
May I ask how to do that with the package? I just followed the:

from bioservices.uniprot import UniProt
u = UniProt(verbose=False)

which I found in the documentation

**Comment by tmdecker** [comment] 2018-11-05 21:41
Hi, I have exactly the same Problem as asulit08: Either the mapping function returns the Uniprot entry as a dictionary of the html code or I receive an IndexError.
I'm using Python 3.6.6, bioservices 1.5.2 on macOS Mojave 10.14.1

**Comment by cokelaer** [comment] 2018-11-28 15:35
from bioservices import UniProt
    u = UniProt()
    text_result = : u.search("P43403")
    u.mapping("ACC", "KEGG_ID", "P43403")

returns

    defaultdict(list, {'P43403': ['hsa:7535']})

**Comment by tmdecker** [comment] 2018-11-28 18:34
Unfortunately, this doesn't work for me. For me it still returns the whole html as dict:

```defaultdict(list,
            {'SYSTEM': ['"about:legacy-compat">'],
             '<html': ['xmlns="http://www.w3.org/1999/xhtml"'],
             'lang="en"': ['xml:lang="en"><head><title>Retrieve/ID'],
             'mapping</title><meta': ['content="IE=edge"'],
             'http-equiv="X-UA-Compatible"/><meta': ['content="text/html;'],
             'charset=UTF-8"': ['http-equiv="Content-Type"/><meta'],
             'content="width=device-width,': ['initial-scale=1"'], ...

**Comment by cokelaer** [comment] 2019-01-11 09:43
In version 1.6.0, we use https instead of http. The examples shown above works well for me. 
Please try with the newest version available on pypi and let me know whether the issue is still there. If so, use the following code to get more information and post them:

    from bioservices import UniProt
    u = UniProt(cache=False, verbose=True)
    u.logging.level = "DEBUG"
    u.mapping("ACC", "KEGG_ID", "P43403")

**Comment by ricosaurus** [comment] 2019-01-17 16:43
As a followup to the IndexError, I set a debugging trace in mapping.  The field mapping so far looks off, and the list of keys has one more entry than the list of values, which I presume is giving the IndexError:

> > /home/richard/anaconda3/envs/pytorch/lib/python3.6/site-packages/bioservices/uniprot.py(359)mapping()
    358             values = result[1::2]
--> 359             for i, key in enumerate(keys):
    360                 result_dict[key].append(values[i])

ipdb> result_dict                                                                                                                                                                                           
defaultdict(<class 'list'>, {'Entry': ['name'], 'Status': ['Protein'], 'names': ['Gene', 'Organism'], 'Length': ['narG'], 'A0A023CP34': ['A0A023CP34_9BACI'], 'unreviewed': ['Nitrate']})
ipdb> i                                                                                                                                                                                                     
6
ipdb> len(values)                                                                                                                                                                                           
31251
ipdb> len(keys)                                                                                                                                                                                             
31252
"

**Comment by ricosaurus** [comment] 2019-01-17 17:12
Clearly the service is returning a different format now than expected (or I have failed to use the correct procedure).  For the above query, a string is returned with many more fields than the requested ACC are returned as a header column, followed by the records separated by newline, the fields by tab.  So clearly splitting on white space won't work with this return string:

    336         params = {'from': fr, 'to': to, 'format': "tab", 'query': query}
    337         result = self.http_post(url, frmt="txt", data=params)
    338 
    339         # changes in version 1.1.1 returns a dictionary instead of list
    340         try:
    341             result = result.split()
    342             del result[0]
    343             del result[0]
    344         except:
    345             self.logging.warning("Results seems empty...returning empty dictionary.")
    346             return {}
    347 

result[0:500] at line 337 before split:

> 'yourlist:M201901176746803381A1F0E0DB47453E0216320D179F03F\tEntry\tEntry name\tStatus\tProtein names\tGene names\tOrganism\tLength\nnarG\tA0A023CP34\tA0A023CP34_9BACI\tunreviewed\tNitrate reductase A subunit alpha\tnarG H839_07214\tParageobacillus genomosp. 1\t1227\nnarG\tA0A023DDB3\tA0A023DDB3_9BACI\tunreviewed\tNitrate reductase alpha subunit\tnarG GCA01S_013_00290\tParageobacillus caldoxylosilyticus NBRC 107762\t1227\nnarG\tA0A023DIW1\tA0A023DIW1_9BACI\tunreviewed\tNitrate reductase alpha subunit\tnarG GCA01S_061_00260\tPa'

**Comment by ricosaurus** [comment] 2019-01-17 19:05
Following up with return values.  It looks like using 'ACC' as the 'to' field in params does not retrieve the key, value pairs.  But using 'ID' seems to work as expected.

**Comment by ricosaurus** [comment] 2019-01-17 19:11
Ok -- 'AC' for 'accession number', but no longer 'ACC'.  I believe that was my problem.

**Comment by asulit08** [comment] 2019-02-05 04:31
Hi again! After some of the updates described here, I have tried to download the most recent conda installation of bioservices (1.6.0) and it appears to be working (that is, my prior problems are not present anymore). I tried running the same u.mapping command in the previous version I used (1.5.2) and the errors are still there so I guess the errors have been solved by the updates. However, I am encountering inconsistencies when using u.search:

when i use the command: 
u.search("A4WGV3.1", columns="go-id")

I get the result:
'Gene ontology IDs\nGO:0003689; GO:0005524; GO:0006260\n'

BUT not everytime I use this command. There are times when I get an empty string even when I am using the exact same command. I would like to ask if you may know why this is and how to avoid it?

**Comment by ricosaurus** [comment] 2019-02-05 15:14
Probably related issue with u.mapping from 'AC' to 'UNIPARC'
the result returned to bioservices.mapping from the service contains extraneous fields and thus breaks the mapping code which assumes only the two fields requested.

Eg here is the 'result' from a trace set at bottom of the bioservice mapping method.  The service must have changed -- now they return all these fields instead of the two requested.  

    356             keys = result[0::2]
    357             values = result[1::2]
    358             for i, key in enumerate(keys):
--> 359                 result_dict[key].append(values[i])
    360         return result_dict
    361 

result[0:20]
['Organisms', 'UniProtKB', 'First', 'seen', 'Last', 'seen', 'Length', 'A0A009EAE1', 'UPI00044FA690', 'Acinetobacter', 'baumannii', '348935;', 'Acinetobacter', 'baumannii', 'A0A009EAE1;', '2014-04-25', '2019-01-16', '352', 'A0A009EAR0', 'UPI00044E87D8']

**Comment by asulit08** [comment] 2019-02-06 21:01
> Hi again! After some of the updates described here, I have tried to download the most recent conda installation of bioservices (1.6.0) and it appears to be working (that is, my prior problems are not present anymore). I tried running the same u.mapping command in the previous version I used (1.5.2) and the errors are still there so I guess the errors have been solved by the updates. However, I am encountering inconsistencies when using u.search:
> 
> when i use the command:
> u.search("A4WGV3.1", columns="go-id")
> 
> I get the result:
> 'Gene ontology IDs\nGO:0003689; GO:0005524; GO:0006260\n'
> 
> BUT not everytime I use this command. There are times when I get an empty string even when I am using the exact same command. I would like to ask if you may know why this is and how to avoid it?

I've done a few more trials with u.search and also getting  inconsistencies with your example "P43403". I just use u.search("P43403") which I assume will give a tab formatted output. It does but I think it gives other entries along with it, not just P43403:

Entry	Entry name	Status	Protein names	Gene names	Organism	Length
P43403	ZAP70_HUMAN	reviewed	Tyrosine-protein kinase ZAP-70 (EC 2.7.10.2) (70 kDa zeta-chain associated protein) (Syk-related tyrosine kinase)	ZAP70 SRK	Homo sapiens (Human)	619
Q9Y2R2	PTN22_HUMAN	reviewed	Tyrosine-protein phosphatase non-receptor type 22 (EC 3.1.3.48) (Hematopoietic cell protein-tyrosine phosphatase 70Z-PEP) (Lymphoid phosphatase) (LyP) (PEST-domain phosphatase) (PEP)	PTPN22 PTPN8	Homo sapiens (Human)	807
P00533	EGFR_HUMAN	reviewed	Epidermal growth factor receptor (EC 2.7.10.1) (Proto-oncogene c-ErbB-1) (Receptor tyrosine-protein kinase erbB-1)	EGFR ERBB ERBB1 HER1	Homo sapiens (Human)	1210
P22681	CBL_HUMAN	reviewed	E3 ubiquitin-protein ligase CBL (EC 2.3.2.27) (Casitas B-lineage lymphoma proto-oncogene) (Proto-oncogene c-Cbl) (RING finger protein 55) (RING-type E3 ubiquitin transferase CBL) (Signal transduction protein CBL)	CBL CBL2 RNF55	Homo sapiens (Human)	906
P20963	CD3Z_HUMAN	reviewed	T-cell surface glycoprotein CD3 zeta chain (T-cell receptor T3 zeta chain) (CD antigen CD247)	CD247 CD3Z T3Z TCRZ	Homo sapiens (Human)	164
Q8BGG7	UBS3B_MOUSE	reviewed	Ubiquitin-associated and SH3 domain-containing protein B (EC 3.1.3.48) (Cbl-interacting protein p70) (Suppressor of T-cell receptor signaling 1) (STS-1) (T-cell ubiquitin ligand 2) (TULA-2) (Tyrosine-protein phosphatase STS1/TULA2)	Ubash3b Sts1	Mus musculus (Mouse)	638
P06239	LCK_HUMAN	reviewed	Tyrosine-protein kinase Lck (EC 2.7.10.2) (Leukocyte C-terminal Src kinase) (LSK) (Lymphocyte cell-specific protein-tyrosine kinase) (Protein YT16) (Proto-oncogene Lck) (T cell-specific protein-tyrosine kinase) (p56-LCK)	LCK	Homo sapiens (Human)	509
P10721	KIT_HUMAN	reviewed	Mast/stem cell growth factor receptor Kit (SCFR) (EC 2.7.10.1) (Piebald trait protein) (PBT) (Proto-oncogene c-Kit) (Tyrosine-protein kinase Kit) (p145 c-kit) (v-kit Hardy-Zuckerman 4 feline sarcoma viral oncogene homolog) (CD antigen CD117)	KIT SCFR	Homo sapiens (Human)	976
P07766	CD3E_HUMAN	reviewed	T-cell surface glycoprotein CD3 epsilon chain (T-cell surface antigen T3/Leu-4 epsilon chain) (CD antigen CD3e)	CD3E T3E	Homo sapiens (Human)	207
P08581	MET_HUMAN	reviewed	Hepatocyte growth factor receptor (HGF receptor) (EC 2.7.10.1) (HGF/SF receptor) (Proto-oncogene c-Met) (Scatter factor receptor) (SF receptor) (Tyrosine-protein kinase Met)	MET	Homo sapiens (Human)	1390
Q8N1K5	THMS1_HUMAN	reviewed	Protein THEMIS (Thymocyte-expressed molecule involved in selection)	THEMIS C6orf190 C6orf207	Homo sapiens (Human)	641

When i tried this again, i got the results for only two entries: 

_Entry	Entry name	Status	Protein names	Gene names	Organism	Length
F9XDX0	F9XDX0_ZYMTI	unreviewed	DNA helicase (EC 3.6.4.12)	MYCGRDRAFT_43403	Zymoseptoria tritici (strain CBS 115943 / IPO323) (Speckled leaf blotch fungus) (Septoria tritici)	1043
P43403	ZAP70_HUMAN	reviewed	Tyrosine-protein kinase ZAP-70 (EC 2.7.10.2) (70 kDa zeta-chain associated protein) (Syk-related tyrosine kinase)	ZAP70 SRK	Homo sapiens (Human)	619_

(Also the same with my original trial for "A4WGV3.1" wherein sometimes I am given a result, and sometimes I do not get anything. 

I would like your take on this and if maybe there is some command that I am not doing correctly. Thank you

**Comment by ricosaurus** [comment] 2019-02-07 17:55
I haven't had any success getting UniProt mapping via bioservices the last few days -- was getting full table results rather than the requested map, now getting nothing.  I suspect it is a UniProt server issue but don't know.

**Comment by cokelaer** [comment] 2020-02-23 23:26
This seems to be a recurrent issue on uniprot services. As far as I am concerned, this works for me (24th Feb 2020) with latest version of bioservices (1.7.0) and python 3.5.5 and 3.6.7
```
from bioservices import UniProt
u = UniProt()
u.mapping("ACC", "KEGG_ID", query='P43403')
```

**Comment by cokelaer** [comment] 2020-03-12 11:41
Some updates and comments before closing this issue @ricosaurus:
@asulit08:


```I've done a few more trials with u.search and also getting inconsistencies with your example "P43403". I just use u.search("P43403") which I assume will give a tab formatted output. It does but I think it gives other entries along with it, not just P43403```

When using the uniprot.search function, this mimics what is going on on uniprot website *search* box. When you search for a string, several candidates are possible. The first one is the most relevant though. You can use the *limit=1* argument to return only the first entry.

```when i use the command:
u.search("A4WGV3.1", columns="go-id")

I get the result:
'Gene ontology IDs\nGO:0003689; GO:0005524; GO:0006260\n'

BUT not everytime I use this command. There are times when I get an empty string even when I am using the exact same command. I would like to ask if you may know why this is and how to avoid it?
```

```
u.search("A4WGV3.1") 
```
returns nothing in my case but 

```
u.search("A4WGV3") 
```

does. Maybe the version .1 is obsolete. This may happen. 
If you get different results, that worrysome. Here, this is not different, the results may be empty. In that case, I would say that the response was too slow. I do not have other ideas at that point to explain the fact that sometimes it is empty, and sometimes it is not

**Closed** 2020-03-12 11:41 UTC
Labels: bug, help wanted, question
